/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Entity.Game;
import Entity.User;
import Utils.DatabaseHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang's PC
 */
public class ListGameRes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListGameRes
     */
    String setModel[] = new String[]{"Mã nhân viên", "Tên nhân viên", "Số đăng ký", "Ngày đăng ký"};
    String sql = "SELECT [user_id], name, numberGame, dateRes FROM [user] INNER JOIN [game] ON [user].[user_id] = [game].userid";
    DefaultTableModel dtm = new DefaultTableModel(setModel, 0);
    ArrayList<Game> lstGame = new ArrayList<>();

    public ArrayList<Game> getListGame() {
        DatabaseHelper dtb = new DatabaseHelper();
        Game g;
        try {
            ResultSet rs = dtb.selectData(sql);
            while (rs.next()) {
                g = new Game(rs.getInt("user_id"), rs.getString("name"), rs.getInt("numberGame"), rs.getString("dateRes"));
                lstGame.add(g);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ListGameRes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lstGame;
    }

    private void setData() {
        lstGame = this.getListGame();
        for (int i = 0; i < lstGame.size(); i++) {
            Game get = lstGame.get(i);
            Object data[] = {get.getId(), get.getName(), get.getNum(), get.getDate()};
            dtm.addRow(data);
        }
        jTable1.setModel(dtm);

    }

    public ListGameRes() {
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Danh sách đăng ký");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Xóa dữ liệu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
