/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import Entity.User;
import ImplementInterface.UserImpl;
import InternalFrame.ChangePass;

import InternalFrame.QuanLyNhanVien;
import InternalFrame.DangNhap;
import InternalFrame.DanhMuc;
import InternalFrame.OrderFrame;
import InternalFrame.QuanLyDanhMuc;
import InternalFrame.QuanLySanPham;
import InternalFrame.SanPham;
import InternalFrame.GameRes;
import InternalFrame.ListGameRes;
import InternalFrame.playGame;
import Utils.Security;
import Utils.Utils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Hoang's PC
 */
public class MainFrame extends javax.swing.JFrame implements DangNhap.Callback {

    /**
     * Creates new form MainFrame
     *
     * @param role Số phân quyền truy cập
     */
    private static int uRole;

//    private void showLogin() {
//        DangNhap loginFrame = DangNhap.getInstance();
//        if (!checkOnly(loginFrame)) {
//            MainDesktopPain.add(loginFrame);
//            centerJIF(loginFrame);
//        } else {
//            loginFrame.show();
//        }
//    }
    public static String welcome, notlogin;

    private void loginTrue(String name) {
        tongquan.setEnabled(true);
        quanly.setEnabled(true);
        dathang.setEnabled(true);
        baocao.setEnabled(true);
        game.setEnabled(true);
        nhanvien.setEnabled(false);
        dangxuat.setEnabled(true);
        doimatkhau.setEnabled(true);
        xinchao.setText(welcome + " " + name + "!");
    }

    public void loginFalse() {
        Security.curentLogin = null;
        tongquan.setEnabled(false);
        quanly.setEnabled(false);
        dathang.setEnabled(false);
        baocao.setEnabled(false);
        game.setEnabled(false);
        dangxuat.setEnabled(false);
        doimatkhau.setEnabled(false);
        xinchao.setText(notlogin);
    }

    public boolean checkOnly(JInternalFrame innerFrame) {
        JInternalFrame[] arrFrame = MainDesktopPain.getAllFrames();
        for (JInternalFrame frame : arrFrame) {
            if (frame.getClass().getName() == innerFrame.getClass().getName()) {
                return true;
            }
        }
        return false;
    }

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = MainDesktopPain.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    public void showFrame(JInternalFrame jintr) {
        if (!checkOnly(jintr)) {
            MainDesktopPain.add(jintr);
            centerJIF(jintr);
        }
    }

    private void setMaxSize() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(dim);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void changeLanguage() {
        ResourceBundle rb = Utils.getLocale();
        welcome = rb.getString("welcome");
        notlogin = rb.getString("notlogin");
        xinchao.setText(notlogin);
        tongquan.setText(rb.getString("overview"));
        quanly.setText(rb.getString("manage"));
        dathang.setText(rb.getString("order"));
        baocao.setText(rb.getString("report"));
        hethong.setText(rb.getString("system"));
        game.setText(rb.getString("game"));
        sanpham.setText(rb.getString("product"));
        danhmuc.setText(rb.getString("category"));
        nhanvien.setText(rb.getString("employees"));
        dangnhap.setText(rb.getString("login"));
        doimatkhau.setText(rb.getString("changepass"));
        dangxuat.setText(rb.getString("logout"));
        ngonngu.setText(rb.getString("language"));
        tiengviet.setText(rb.getString("vietnam"));
        tienganh.setText(rb.getString("english"));
        register.setText(rb.getString("registergame"));
        listregister.setText(rb.getString("listreggame"));
        start.setText(rb.getString("startgame"));
    }

    public MainFrame() {
        initComponents();
        DangNhap dn = new DangNhap(this, true);
        dn.setupCallbackObject(this);
        loginFalse();
        setMaxSize();
        showFrame(dn);
        changeLanguage();
//        showLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainDesktopPain = new javax.swing.JDesktopPane();
        xinchao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        tongquan = new javax.swing.JMenu();
        quanly = new javax.swing.JMenu();
        sanpham = new javax.swing.JMenuItem();
        danhmuc = new javax.swing.JMenuItem();
        nhanvien = new javax.swing.JMenuItem();
        baocao = new javax.swing.JMenu();
        dathang = new javax.swing.JMenu();
        hethong = new javax.swing.JMenu();
        dangnhap = new javax.swing.JMenuItem();
        doimatkhau = new javax.swing.JMenuItem();
        dangxuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ngonngu = new javax.swing.JMenu();
        tiengviet = new javax.swing.JRadioButtonMenuItem();
        tienganh = new javax.swing.JRadioButtonMenuItem();
        game = new javax.swing.JMenu();
        register = new javax.swing.JMenuItem();
        listregister = new javax.swing.JMenuItem();
        start = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProjectJava");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MainDesktopPain.setToolTipText("");

        xinchao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xinchao.setForeground(new java.awt.Color(255, 255, 0));

        MainDesktopPain.setLayer(xinchao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainDesktopPainLayout = new javax.swing.GroupLayout(MainDesktopPain);
        MainDesktopPain.setLayout(MainDesktopPainLayout);
        MainDesktopPainLayout.setHorizontalGroup(
            MainDesktopPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDesktopPainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xinchao, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        MainDesktopPainLayout.setVerticalGroup(
            MainDesktopPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDesktopPainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xinchao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        tongquan.setText("Tổng quan");
        jMenuBar1.add(tongquan);

        quanly.setText("Quản Lý");

        sanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Ecommerce-Product-icon.png"))); // NOI18N
        sanpham.setText("Sản Phẩm");
        sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanphamActionPerformed(evt);
            }
        });
        quanly.add(sanpham);

        danhmuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/category-icon.png"))); // NOI18N
        danhmuc.setText("Danh Mục");
        danhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhmucActionPerformed(evt);
            }
        });
        quanly.add(danhmuc);

        nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Office-Customer-Male-Light-icon.png"))); // NOI18N
        nhanvien.setText("Nhân Viên");
        nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanvienActionPerformed(evt);
            }
        });
        quanly.add(nhanvien);

        jMenuBar1.add(quanly);

        baocao.setText("Báo cáo");
        baocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baocaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(baocao);

        dathang.setText("Order");
        dathang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dathangMouseClicked(evt);
            }
        });
        jMenuBar1.add(dathang);

        hethong.setText("Hệ thống");
        hethong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hethongMouseClicked(evt);
            }
        });
        hethong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hethongActionPerformed(evt);
            }
        });

        dangnhap.setText("Đăng nhập");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        hethong.add(dangnhap);

        doimatkhau.setText("Đổi mật khẩu");
        doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doimatkhauActionPerformed(evt);
            }
        });
        hethong.add(doimatkhau);

        dangxuat.setText("Đăng xuất");
        dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatActionPerformed(evt);
            }
        });
        hethong.add(dangxuat);
        hethong.add(jSeparator1);

        ngonngu.setText("Ngôn ngữ");

        buttonGroup1.add(tiengviet);
        tiengviet.setSelected(true);
        tiengviet.setText("Tiếng Việt");
        tiengviet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiengvietActionPerformed(evt);
            }
        });
        ngonngu.add(tiengviet);

        buttonGroup1.add(tienganh);
        tienganh.setText("Tiếng Anh");
        tienganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tienganhActionPerformed(evt);
            }
        });
        ngonngu.add(tienganh);

        hethong.add(ngonngu);

        jMenuBar1.add(hethong);

        game.setText("Game cuối ngày");

        register.setText("Đăng ký");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        game.add(register);

        listregister.setText("Danh sách đăng ký");
        listregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listregisterActionPerformed(evt);
            }
        });
        game.add(listregister);

        start.setText("Bắt đầu chơi");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        game.add(start);

        jMenuBar1.add(game);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainDesktopPain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainDesktopPain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanphamActionPerformed
        try {
            // TODO add your handling code here:
            JInternalFrame sp = new QuanLySanPham();
            showFrame(sp);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sanphamActionPerformed

    private void hethongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hethongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hethongActionPerformed

    private void hethongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hethongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hethongMouseClicked

    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        // TODO add your handling code here:
        MainDesktopPain.removeAll();
        MainDesktopPain.repaint();
        MainDesktopPain.add(xinchao);
        xinchao.setVisible(true);
        DangNhap dn = new DangNhap(this, true);
        dn.setupCallbackObject(this);
        showFrame(dn);
    }//GEN-LAST:event_dangnhapActionPerformed

    private void dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatActionPerformed
        // TODO add your handling code here:
        MainDesktopPain.removeAll();
        MainDesktopPain.repaint();
        MainDesktopPain.add(xinchao);
        xinchao.setVisible(true);
        loginFalse();
    }//GEN-LAST:event_dangxuatActionPerformed

    private void nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanvienActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        showFrame(qlnv);
    }//GEN-LAST:event_nhanvienActionPerformed

    private void danhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhmucActionPerformed
        QuanLyDanhMuc qldm = new QuanLyDanhMuc();
        showFrame(qldm);
    }//GEN-LAST:event_danhmucActionPerformed

    private void dathangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dathangMouseClicked
        try {
            // TODO add your handling code here:
            OrderFrame of = new OrderFrame();
            showFrame(of);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dathangMouseClicked

    private void baocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baocaoMouseClicked
        // TODO add your handling code here: 
        System.out.println(Utils.Language);
    }//GEN-LAST:event_baocaoMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        GameRes g = new GameRes();
        showFrame(g);
    }//GEN-LAST:event_registerActionPerformed

    private void doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doimatkhauActionPerformed
        // TODO add your handling code here:
        ChangePass ch = new ChangePass();
        showFrame(ch);
    }//GEN-LAST:event_doimatkhauActionPerformed

    private void listregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listregisterActionPerformed
        // TODO add your handling code here:
        ListGameRes g = new ListGameRes();
        showFrame(g);
    }//GEN-LAST:event_listregisterActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        playGame p = new playGame();
        showFrame(p);
    }//GEN-LAST:event_startActionPerformed

    private void tiengvietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiengvietActionPerformed
        // TODO add your handling code here:
        Utils.Language = "vi";
        Utils.Country = "VN";
        changeLanguage();
    }//GEN-LAST:event_tiengvietActionPerformed

    private void tienganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tienganhActionPerformed
        // TODO add your handling code here:
        Utils.Language = "en";
        Utils.Country = "US";
        changeLanguage();
    }//GEN-LAST:event_tienganhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainDesktopPain;
    private javax.swing.JMenu baocao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem dangnhap;
    private javax.swing.JMenuItem dangxuat;
    private javax.swing.JMenuItem danhmuc;
    private javax.swing.JMenu dathang;
    private javax.swing.JMenuItem doimatkhau;
    private javax.swing.JMenu game;
    private javax.swing.JMenu hethong;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listregister;
    private javax.swing.JMenu ngonngu;
    private javax.swing.JMenuItem nhanvien;
    private javax.swing.JMenu quanly;
    private javax.swing.JMenuItem register;
    private javax.swing.JMenuItem sanpham;
    private javax.swing.JMenuItem start;
    private javax.swing.JRadioButtonMenuItem tienganh;
    private javax.swing.JRadioButtonMenuItem tiengviet;
    private javax.swing.JMenu tongquan;
    private javax.swing.JLabel xinchao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setRole(User u) {
        loginTrue(u.getName());
        uRole = u.getUserRole();
        switch (uRole) {
            case 1:
                nhanvien.setEnabled(true);
                break;
            case 2:
                quanly.setEnabled(false);
                break;
            case 3:
                break;
            case 4:
                dathang.setEnabled(false);
                break;
            case 5:
                baocao.setEnabled(false);
                break;
        }
    }
}
